# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sinatra-bundles}
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniel Huckstep"]
  s.date = %q{2010-02-21}
  s.description = %q{Bundle CSS and Javascript assets to a single file, compress, and cache them for snappier web experiences.}
  s.email = %q{darkhelmet@darkhelmetlive.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "lib/sinatra/bundles.rb",
     "lib/sinatra/bundles/bundle.rb",
     "lib/sinatra/bundles/helpers.rb",
     "lib/sinatra/bundles/javascript_bundle.rb",
     "lib/sinatra/bundles/stylesheet_bundle.rb",
     "sinatra-bundles.gemspec",
     "spec/app.rb",
     "spec/production_app.rb",
     "spec/public/javascripts/eval.js",
     "spec/public/javascripts/test1.js",
     "spec/public/javascripts/test2.js",
     "spec/public/stylesheets/test1.css",
     "spec/public/stylesheets/test2.css",
     "spec/sinatra-bundles_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "vendor/bin/rackup",
     "vendor/cache/rack-1.1.0.gem",
     "vendor/cache/sinatra-0.10.1.gem",
     "vendor/cache/sinatra-1.0.a.gem",
     "vendor/gems/rack-1.1.0/COPYING",
     "vendor/gems/rack-1.1.0/KNOWN-ISSUES",
     "vendor/gems/rack-1.1.0/RDOX",
     "vendor/gems/rack-1.1.0/README",
     "vendor/gems/rack-1.1.0/SPEC",
     "vendor/gems/rack-1.1.0/bin/rackup",
     "vendor/gems/rack-1.1.0/contrib/rack_logo.svg",
     "vendor/gems/rack-1.1.0/example/lobster.ru",
     "vendor/gems/rack-1.1.0/example/protectedlobster.rb",
     "vendor/gems/rack-1.1.0/example/protectedlobster.ru",
     "vendor/gems/rack-1.1.0/lib/rack.rb",
     "vendor/gems/rack-1.1.0/lib/rack/adapter/camping.rb",
     "vendor/gems/rack-1.1.0/lib/rack/auth/abstract/handler.rb",
     "vendor/gems/rack-1.1.0/lib/rack/auth/abstract/request.rb",
     "vendor/gems/rack-1.1.0/lib/rack/auth/basic.rb",
     "vendor/gems/rack-1.1.0/lib/rack/auth/digest/md5.rb",
     "vendor/gems/rack-1.1.0/lib/rack/auth/digest/nonce.rb",
     "vendor/gems/rack-1.1.0/lib/rack/auth/digest/params.rb",
     "vendor/gems/rack-1.1.0/lib/rack/auth/digest/request.rb",
     "vendor/gems/rack-1.1.0/lib/rack/builder.rb",
     "vendor/gems/rack-1.1.0/lib/rack/cascade.rb",
     "vendor/gems/rack-1.1.0/lib/rack/chunked.rb",
     "vendor/gems/rack-1.1.0/lib/rack/commonlogger.rb",
     "vendor/gems/rack-1.1.0/lib/rack/conditionalget.rb",
     "vendor/gems/rack-1.1.0/lib/rack/config.rb",
     "vendor/gems/rack-1.1.0/lib/rack/content_length.rb",
     "vendor/gems/rack-1.1.0/lib/rack/content_type.rb",
     "vendor/gems/rack-1.1.0/lib/rack/deflater.rb",
     "vendor/gems/rack-1.1.0/lib/rack/directory.rb",
     "vendor/gems/rack-1.1.0/lib/rack/etag.rb",
     "vendor/gems/rack-1.1.0/lib/rack/file.rb",
     "vendor/gems/rack-1.1.0/lib/rack/handler.rb",
     "vendor/gems/rack-1.1.0/lib/rack/handler/cgi.rb",
     "vendor/gems/rack-1.1.0/lib/rack/handler/evented_mongrel.rb",
     "vendor/gems/rack-1.1.0/lib/rack/handler/fastcgi.rb",
     "vendor/gems/rack-1.1.0/lib/rack/handler/lsws.rb",
     "vendor/gems/rack-1.1.0/lib/rack/handler/mongrel.rb",
     "vendor/gems/rack-1.1.0/lib/rack/handler/scgi.rb",
     "vendor/gems/rack-1.1.0/lib/rack/handler/swiftiplied_mongrel.rb",
     "vendor/gems/rack-1.1.0/lib/rack/handler/thin.rb",
     "vendor/gems/rack-1.1.0/lib/rack/handler/webrick.rb",
     "vendor/gems/rack-1.1.0/lib/rack/head.rb",
     "vendor/gems/rack-1.1.0/lib/rack/lint.rb",
     "vendor/gems/rack-1.1.0/lib/rack/lobster.rb",
     "vendor/gems/rack-1.1.0/lib/rack/lock.rb",
     "vendor/gems/rack-1.1.0/lib/rack/logger.rb",
     "vendor/gems/rack-1.1.0/lib/rack/methodoverride.rb",
     "vendor/gems/rack-1.1.0/lib/rack/mime.rb",
     "vendor/gems/rack-1.1.0/lib/rack/mock.rb",
     "vendor/gems/rack-1.1.0/lib/rack/nulllogger.rb",
     "vendor/gems/rack-1.1.0/lib/rack/recursive.rb",
     "vendor/gems/rack-1.1.0/lib/rack/reloader.rb",
     "vendor/gems/rack-1.1.0/lib/rack/request.rb",
     "vendor/gems/rack-1.1.0/lib/rack/response.rb",
     "vendor/gems/rack-1.1.0/lib/rack/rewindable_input.rb",
     "vendor/gems/rack-1.1.0/lib/rack/runtime.rb",
     "vendor/gems/rack-1.1.0/lib/rack/sendfile.rb",
     "vendor/gems/rack-1.1.0/lib/rack/server.rb",
     "vendor/gems/rack-1.1.0/lib/rack/session/abstract/id.rb",
     "vendor/gems/rack-1.1.0/lib/rack/session/cookie.rb",
     "vendor/gems/rack-1.1.0/lib/rack/session/memcache.rb",
     "vendor/gems/rack-1.1.0/lib/rack/session/pool.rb",
     "vendor/gems/rack-1.1.0/lib/rack/showexceptions.rb",
     "vendor/gems/rack-1.1.0/lib/rack/showstatus.rb",
     "vendor/gems/rack-1.1.0/lib/rack/static.rb",
     "vendor/gems/rack-1.1.0/lib/rack/urlmap.rb",
     "vendor/gems/rack-1.1.0/lib/rack/utils.rb",
     "vendor/gems/rack-1.1.0/rack.gemspec",
     "vendor/gems/rack-1.1.0/test/spec_rack_auth_basic.rb",
     "vendor/gems/rack-1.1.0/test/spec_rack_auth_digest.rb",
     "vendor/gems/rack-1.1.0/test/spec_rack_builder.rb",
     "vendor/gems/rack-1.1.0/test/spec_rack_camping.rb",
     "vendor/gems/rack-1.1.0/test/spec_rack_cascade.rb",
     "vendor/gems/rack-1.1.0/test/spec_rack_cgi.rb",
     "vendor/gems/rack-1.1.0/test/spec_rack_chunked.rb",
     "vendor/gems/rack-1.1.0/test/spec_rack_commonlogger.rb",
     "vendor/gems/rack-1.1.0/test/spec_rack_conditionalget.rb",
     "vendor/gems/rack-1.1.0/test/spec_rack_config.rb",
     "vendor/gems/rack-1.1.0/test/spec_rack_content_length.rb",
     "vendor/gems/rack-1.1.0/test/spec_rack_content_type.rb",
     "vendor/gems/rack-1.1.0/test/spec_rack_deflater.rb",
     "vendor/gems/rack-1.1.0/test/spec_rack_directory.rb",
     "vendor/gems/rack-1.1.0/test/spec_rack_etag.rb",
     "vendor/gems/rack-1.1.0/test/spec_rack_fastcgi.rb",
     "vendor/gems/rack-1.1.0/test/spec_rack_file.rb",
     "vendor/gems/rack-1.1.0/test/spec_rack_handler.rb",
     "vendor/gems/rack-1.1.0/test/spec_rack_head.rb",
     "vendor/gems/rack-1.1.0/test/spec_rack_lint.rb",
     "vendor/gems/rack-1.1.0/test/spec_rack_lobster.rb",
     "vendor/gems/rack-1.1.0/test/spec_rack_lock.rb",
     "vendor/gems/rack-1.1.0/test/spec_rack_logger.rb",
     "vendor/gems/rack-1.1.0/test/spec_rack_methodoverride.rb",
     "vendor/gems/rack-1.1.0/test/spec_rack_mock.rb",
     "vendor/gems/rack-1.1.0/test/spec_rack_mongrel.rb",
     "vendor/gems/rack-1.1.0/test/spec_rack_nulllogger.rb",
     "vendor/gems/rack-1.1.0/test/spec_rack_recursive.rb",
     "vendor/gems/rack-1.1.0/test/spec_rack_request.rb",
     "vendor/gems/rack-1.1.0/test/spec_rack_response.rb",
     "vendor/gems/rack-1.1.0/test/spec_rack_rewindable_input.rb",
     "vendor/gems/rack-1.1.0/test/spec_rack_runtime.rb",
     "vendor/gems/rack-1.1.0/test/spec_rack_sendfile.rb",
     "vendor/gems/rack-1.1.0/test/spec_rack_session_cookie.rb",
     "vendor/gems/rack-1.1.0/test/spec_rack_session_memcache.rb",
     "vendor/gems/rack-1.1.0/test/spec_rack_session_pool.rb",
     "vendor/gems/rack-1.1.0/test/spec_rack_showexceptions.rb",
     "vendor/gems/rack-1.1.0/test/spec_rack_showstatus.rb",
     "vendor/gems/rack-1.1.0/test/spec_rack_static.rb",
     "vendor/gems/rack-1.1.0/test/spec_rack_thin.rb",
     "vendor/gems/rack-1.1.0/test/spec_rack_urlmap.rb",
     "vendor/gems/rack-1.1.0/test/spec_rack_utils.rb",
     "vendor/gems/rack-1.1.0/test/spec_rack_webrick.rb",
     "vendor/gems/rack-1.1.0/test/spec_rackup.rb",
     "vendor/gems/sinatra-1.0.a/AUTHORS",
     "vendor/gems/sinatra-1.0.a/CHANGES",
     "vendor/gems/sinatra-1.0.a/LICENSE",
     "vendor/gems/sinatra-1.0.a/README.jp.rdoc",
     "vendor/gems/sinatra-1.0.a/README.rdoc",
     "vendor/gems/sinatra-1.0.a/Rakefile",
     "vendor/gems/sinatra-1.0.a/lib/sinatra.rb",
     "vendor/gems/sinatra-1.0.a/lib/sinatra/base.rb",
     "vendor/gems/sinatra-1.0.a/lib/sinatra/images/404.png",
     "vendor/gems/sinatra-1.0.a/lib/sinatra/images/500.png",
     "vendor/gems/sinatra-1.0.a/lib/sinatra/main.rb",
     "vendor/gems/sinatra-1.0.a/lib/sinatra/showexceptions.rb",
     "vendor/gems/sinatra-1.0.a/lib/sinatra/tilt.rb",
     "vendor/gems/sinatra-1.0.a/sinatra.gemspec",
     "vendor/gems/sinatra-1.0.a/test/base_test.rb",
     "vendor/gems/sinatra-1.0.a/test/builder_test.rb",
     "vendor/gems/sinatra-1.0.a/test/contest.rb",
     "vendor/gems/sinatra-1.0.a/test/erb_test.rb",
     "vendor/gems/sinatra-1.0.a/test/erubis_test.rb",
     "vendor/gems/sinatra-1.0.a/test/extensions_test.rb",
     "vendor/gems/sinatra-1.0.a/test/filter_test.rb",
     "vendor/gems/sinatra-1.0.a/test/haml_test.rb",
     "vendor/gems/sinatra-1.0.a/test/helper.rb",
     "vendor/gems/sinatra-1.0.a/test/helpers_test.rb",
     "vendor/gems/sinatra-1.0.a/test/mapped_error_test.rb",
     "vendor/gems/sinatra-1.0.a/test/middleware_test.rb",
     "vendor/gems/sinatra-1.0.a/test/public/favicon.ico",
     "vendor/gems/sinatra-1.0.a/test/request_test.rb",
     "vendor/gems/sinatra-1.0.a/test/response_test.rb",
     "vendor/gems/sinatra-1.0.a/test/result_test.rb",
     "vendor/gems/sinatra-1.0.a/test/route_added_hook_test.rb",
     "vendor/gems/sinatra-1.0.a/test/routing_test.rb",
     "vendor/gems/sinatra-1.0.a/test/sass_test.rb",
     "vendor/gems/sinatra-1.0.a/test/server_test.rb",
     "vendor/gems/sinatra-1.0.a/test/settings_test.rb",
     "vendor/gems/sinatra-1.0.a/test/sinatra_test.rb",
     "vendor/gems/sinatra-1.0.a/test/static_test.rb",
     "vendor/gems/sinatra-1.0.a/test/templates_test.rb",
     "vendor/gems/sinatra-1.0.a/test/views/error.builder",
     "vendor/gems/sinatra-1.0.a/test/views/error.erb",
     "vendor/gems/sinatra-1.0.a/test/views/error.erubis",
     "vendor/gems/sinatra-1.0.a/test/views/error.haml",
     "vendor/gems/sinatra-1.0.a/test/views/error.sass",
     "vendor/gems/sinatra-1.0.a/test/views/foo/hello.test",
     "vendor/gems/sinatra-1.0.a/test/views/hello.builder",
     "vendor/gems/sinatra-1.0.a/test/views/hello.erb",
     "vendor/gems/sinatra-1.0.a/test/views/hello.erubis",
     "vendor/gems/sinatra-1.0.a/test/views/hello.haml",
     "vendor/gems/sinatra-1.0.a/test/views/hello.sass",
     "vendor/gems/sinatra-1.0.a/test/views/hello.test",
     "vendor/gems/sinatra-1.0.a/test/views/layout2.builder",
     "vendor/gems/sinatra-1.0.a/test/views/layout2.erb",
     "vendor/gems/sinatra-1.0.a/test/views/layout2.erubis",
     "vendor/gems/sinatra-1.0.a/test/views/layout2.haml",
     "vendor/gems/sinatra-1.0.a/test/views/layout2.test",
     "vendor/specifications/rack-1.1.0.gemspec",
     "vendor/specifications/sinatra-0.10.1.gemspec",
     "vendor/specifications/sinatra-1.0.a.gemspec"
  ]
  s.homepage = %q{http://github.com/darkhelmet/sinatra-bundles}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Easy asset bundling for sinatra}
  s.test_files = [
    "spec/app.rb",
     "spec/production_app.rb",
     "spec/sinatra-bundles_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rainpress>, [">= 0"])
      s.add_runtime_dependency(%q<packr>, [">= 0"])
      s.add_runtime_dependency(%q<sinatra>, [">= 1.0.a"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<rack-test>, [">= 0.5.3"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<rainpress>, [">= 0"])
      s.add_dependency(%q<packr>, [">= 0"])
      s.add_dependency(%q<sinatra>, [">= 1.0.a"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<rack-test>, [">= 0.5.3"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<rainpress>, [">= 0"])
    s.add_dependency(%q<packr>, [">= 0"])
    s.add_dependency(%q<sinatra>, [">= 1.0.a"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<rack-test>, [">= 0.5.3"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

